---
title: Triggering functions with buttons
hero_image: images/banner.png
description: How to trigger function calls with buttons
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - 
    title: Triggering function calls with buttons
