---
title: Λειτουργίες ενεργοποίησης με πλήκτρα (buttons)
hero_image: images/banner.png
description: Πώς να ενεργοποιήσεις λειτουργίες με πλήκτρα
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - title: Εκκίνηση λειτουργιών με χρήση πλήκτρων (buttons)
